/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ACButton } from './aCButton';
import { AirConRangeModes } from './airConRangeModes';

export class AirConRange {
    'modes'?: AirConRangeModes;
    'fixedButtons'?: Array<ACButton>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "modes",
            "baseName": "modes",
            "type": "AirConRangeModes"
        },
        {
            "name": "fixedButtons",
            "baseName": "fixedButtons",
            "type": "Array<ACButton>"
        }    ];

    static getAttributeTypeMap() {
        return AirConRange.attributeTypeMap;
    }
}

