/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirConRange } from './airConRange';

export class AirCon {
    'range'?: AirConRange;
    'tempUnit'?: AirCon.TempUnitEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "range",
            "baseName": "range",
            "type": "AirConRange"
        },
        {
            "name": "tempUnit",
            "baseName": "tempUnit",
            "type": "AirCon.TempUnitEnum"
        }    ];

    static getAttributeTypeMap() {
        return AirCon.attributeTypeMap;
    }
}

export namespace AirCon {
    export enum TempUnitEnum {
        empty = <any> '',
        c = <any> 'c',
        f = <any> 'f'
    }
}
