/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirDirection } from './airDirection';
import { AirVolume } from './airVolume';

export class AirConRangeMode {
    'temp'?: Array<string>;
    'vol'?: Array<AirVolume>;
    'dir'?: Array<AirDirection>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "temp",
            "baseName": "temp",
            "type": "Array<string>"
        },
        {
            "name": "vol",
            "baseName": "vol",
            "type": "Array<AirVolume>"
        },
        {
            "name": "dir",
            "baseName": "dir",
            "type": "Array<AirDirection>"
        }    ];

    static getAttributeTypeMap() {
        return AirConRangeMode.attributeTypeMap;
    }
}

