/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirConRangeMode } from './airConRangeMode';

export class AirConRangeModes {
    'cool'?: AirConRangeMode;
    'warm'?: AirConRangeMode;
    'dry'?: AirConRangeMode;
    'blow'?: AirConRangeMode;
    'auto'?: AirConRangeMode;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cool",
            "baseName": "cool",
            "type": "AirConRangeMode"
        },
        {
            "name": "warm",
            "baseName": "warm",
            "type": "AirConRangeMode"
        },
        {
            "name": "dry",
            "baseName": "dry",
            "type": "AirConRangeMode"
        },
        {
            "name": "blow",
            "baseName": "blow",
            "type": "AirConRangeMode"
        },
        {
            "name": "auto",
            "baseName": "auto",
            "type": "AirConRangeMode"
        }    ];

    static getAttributeTypeMap() {
        return AirConRangeModes.attributeTypeMap;
    }
}

