/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ACButton } from './aCButton';
import { AirDirection } from './airDirection';
import { AirVolume } from './airVolume';
import { OperationMode } from './operationMode';

export class AirConParams {
    /**
    * The temperature in string format. The unit is described in Aircon object. The range of Temperatures which the air conditioner accepts depends on the air conditioner model and operation mode. Check the \'AirConRangeMode\' information in the response for the range of the particular air conditioner model and operation mode.
    */
    'temp'?: string;
    'mode'?: OperationMode;
    'vol'?: AirVolume;
    'dir'?: AirDirection;
    'button'?: ACButton;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "temp",
            "baseName": "temp",
            "type": "string"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "OperationMode"
        },
        {
            "name": "vol",
            "baseName": "vol",
            "type": "AirVolume"
        },
        {
            "name": "dir",
            "baseName": "dir",
            "type": "AirDirection"
        },
        {
            "name": "button",
            "baseName": "button",
            "type": "ACButton"
        }    ];

    static getAttributeTypeMap() {
        return AirConParams.attributeTypeMap;
    }
}

