/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Empty means automatic. Numbers express the amount of volume. The range of AirVolumes which the air conditioner accepts depends on the air conditioner model and operation mode. Check the \'AirConRangeMode\' information in the response for the range of the particular air conditioner model and operation mode.
*/
export enum AirVolume {
    empty = <any> '',
    auto = <any> 'auto',
    _1 = <any> '1',
    _2 = <any> '2',
    _3 = <any> '3',
    _4 = <any> '4',
    _5 = <any> '5',
    _6 = <any> '6',
    _7 = <any> '7',
    _8 = <any> '8',
    _9 = <any> '9',
    _10 = <any> '10'
}
