/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirConParams } from './airConParams';
import { ApplianceModel } from './applianceModel';

export class ApplianceModelAndParam {
    'model'?: ApplianceModel;
    'params'?: AirConParams;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "model",
            "baseName": "model",
            "type": "ApplianceModel"
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "AirConParams"
        }    ];

    static getAttributeTypeMap() {
        return ApplianceModelAndParam.attributeTypeMap;
    }
}

