/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Type of the appliance. \"AC\" (Air conditioner), \"TV\" and \"LIGHT\" are 1st class citizen appliance, which is included in our IRDB (InfraRed signals DataBase). The \"ApplianceModel\" stores meta data about the appliance. We provide AC specific UI. Everything else is \"IR\". We just learn the signals from the remote and store them, and when users tap the button on the smartphone app, our server sends it through Remo.
*/
export enum ApplianceType {
    aC = <any> 'AC',
    tV = <any> 'TV',
    lIGHT = <any> 'LIGHT',
    iR = <any> 'IR'
}
