/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AirCon } from './airCon';
import { AirConParams } from './airConParams';
import { ApplianceModel } from './applianceModel';
import { ApplianceType } from './applianceType';
import { DeviceCore } from './deviceCore';
import { LIGHT } from './lIGHT';
import { Signal } from './signal';
import { SmartMeter } from './smartMeter';
import { TV } from './tV';

export class Appliance {
    'id'?: string;
    'device'?: DeviceCore;
    'model'?: ApplianceModel;
    'nickname'?: string;
    /**
    * Basename of the image file included in the app. Ex: \"ico_ac_1\" 
    */
    'image'?: string;
    'type'?: ApplianceType;
    'settings'?: AirConParams;
    'aircon'?: AirCon;
    'signals'?: Array<Signal>;
    'tv'?: TV;
    'light'?: LIGHT;
    'smartMeter'?: SmartMeter;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "DeviceCore"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "ApplianceModel"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApplianceType"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "AirConParams"
        },
        {
            "name": "aircon",
            "baseName": "aircon",
            "type": "AirCon"
        },
        {
            "name": "signals",
            "baseName": "signals",
            "type": "Array<Signal>"
        },
        {
            "name": "tv",
            "baseName": "tv",
            "type": "TV"
        },
        {
            "name": "light",
            "baseName": "light",
            "type": "LIGHT"
        },
        {
            "name": "smartMeter",
            "baseName": "smart_meter",
            "type": "SmartMeter"
        }    ];

    static getAttributeTypeMap() {
        return Appliance.attributeTypeMap;
    }
}

