/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DeviceCore {
    'id'?: string;
    'name'?: string;
    'temperatureOffset'?: number;
    'humidityOffset'?: number;
    'createdAt'?: Date;
    'updatedAt'?: Date;
    'firmwareVersion'?: string;
    'macAddress'?: string;
    'serialNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "temperatureOffset",
            "baseName": "temperature_offset",
            "type": "number"
        },
        {
            "name": "humidityOffset",
            "baseName": "humidity_offset",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "firmwareVersion",
            "baseName": "firmware_version",
            "type": "string"
        },
        {
            "name": "macAddress",
            "baseName": "mac_address",
            "type": "string"
        },
        {
            "name": "serialNumber",
            "baseName": "serial_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DeviceCore.attributeTypeMap;
    }
}

