/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The ECHONET lite properties fetched from the appliance. See \"Detailed Requirements for ECHONET Device Objects\" for more details. ref. https://echonet.jp/spec_object_rl_en/ 
*/
export class EchonetLiteProperty {
    'name'?: string;
    /**
    * ECHONET Property
    */
    'epc'?: number;
    'val'?: string;
    'updatedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "epc",
            "baseName": "epc",
            "type": "number"
        },
        {
            "name": "val",
            "baseName": "val",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return EchonetLiteProperty.attributeTypeMap;
    }
}

