/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The range of OperationModes which the air conditioner accepts depends on the air conditioner model. Check the \'AirConRangeMode\' information in the response for the range of the particular air conditioner model.
*/
export enum OperationMode {
    empty = <any> '',
    cool = <any> 'cool',
    warm = <any> 'warm',
    dry = <any> 'dry',
    blow = <any> 'blow',
    auto = <any> 'auto'
}
