/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The reference key to SensorValue means \"te\" = temperature, \"hu\" = humidity, \"il\" = illumination, \"mo\" = movement. The val of \"mo\" is always 1 and when movement event is captured created_at is updated. 
*/
export class SensorValue {
    'val'?: number;
    'createdAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "val",
            "baseName": "val",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return SensorValue.attributeTypeMap;
    }
}

