/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EchonetLiteProperty } from './echonetLiteProperty';

export class SmartMeter {
    'echonetliteProperties'?: Array<EchonetLiteProperty>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "echonetliteProperties",
            "baseName": "echonetlite_properties",
            "type": "Array<EchonetLiteProperty>"
        }    ];

    static getAttributeTypeMap() {
        return SmartMeter.attributeTypeMap;
    }
}

