/**
 * Nature API
 * Read/Write Nature Remo
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TVState {
    'input'?: TVState.InputEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "input",
            "baseName": "input",
            "type": "TVState.InputEnum"
        }    ];

    static getAttributeTypeMap() {
        return TVState.attributeTypeMap;
    }
}

export namespace TVState {
    export enum InputEnum {
        t = <any> 't',
        bs = <any> 'bs',
        cs = <any> 'cs'
    }
}
